site_name: biolxy的知识库
site_url: https://biolxy.github.io/
site_author: biolxy
copyright: biolxy
repo_name: biolxy
theme:
  name: material # 主题
  # [切换日间模式和夜间模式]
  # ref: https://zhuanlan.zhihu.com/p/685390406  https://eric2003.github.io/Prometheus/home/
  palette:
    # 日间模式
    - scheme: default
      # 主颜色
      primary: indigo
      # 链接等可交互元件的高亮色
      accent: orange
      toggle:
        # 图标
        icon: material/weather-night
        # 鼠标悬浮提示
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    # 使用 Tab 来进行分类
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    - navigation.top
    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    - navigation.indexes
    # 打开 Tab 时左侧目录全部展开
    - navigation.expand
    # 搜索输入一些字母时推荐补全整个单词
    - search.suggest
    # 搜索的关键词文章加入高亮
    - search.highlight
    # 可以通过按钮复制代码
    - content.code.copy
    # [点击按钮跳转至 GitHub 修改 Markdown 源文件]
    - content.action.edit
  language: zh # 一些提示性的文字会变成中文
  icon:
    # [添加 GitHub 仓库]
    repo: https://github.com/biolxy
markdown_extensions:
  # Python Markdown
  - abbr
  - tables
  - attr_list
  - def_list
  # [Markdown footnote 语法支持]
  - footnotes
  # [Markdown 提示]
  - admonition
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
      # Latex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      # 显示行号
      linenums: true
      # 显示编程语言名称
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - offline
  # [给单篇文章添加标签]
  - tags
  - search:
      lang:
        - zh
        - en


extra:
  # [添加社交网络图标和链接]
  # name 会在鼠标悬浮时提示
  social: # icons
    - name: GitHub | biolxy
      icon: fontawesome/brands/github
      link: https://github.com/biolxy

# 文档布局
nav:
- Home: index.md
- 博客:
  - Linux安装rar解压软件: blog/2018-12-18-Linux安装rar解压软件.md
  - git开发功能分支标准流程: blog/2018-12-4-git开发功能分支标准流程.md
  - 简单的markdown博客的测试: blog/2018-7-30-简单的markdown博客的测试.md
  - Github个人博客搭建记录: blog/2018-7-31-Github个人博客搭建记录.md
  - 你用的是哪个版本的rename: blog/2018-8-15-你用的是哪个版本的rename.md
  - 生物信息学常用的Linux命令: blog/2018-8-1-生物信息学常用的Linux命令.md
  - 初识GeneSignature : blog/2018-8-3-初识GeneSignature.md
  - 统计学中常用的RR-OR-HR的含义及区别: blog/2018-8-5-统计学中常用的RR-OR-HR的含义及区别.md
  - 将cd和ls两个命令组合起来使用: blog/2018-9-12-将cd和ls两个命令组合起来使用.md
  - 基于已有的image创建dockerimages : blog/2018-9-19-基于已有的image创建dockerimages.md
  - 你是否工作的开心？: blog/2018-9-21-你是否工作的开心？.md
  - 软件著作权申请流程: blog/2018-9-21-软件著作权申请流程.md
  - PyClone的安装报错及解决: blog/2018-9-4-PyClone的安装报错及解决.md
  - R语言使用: blog/2018-9-5-R语言使用.md
  - 开源编程数据汇总: blog/2019-01-17-开源编程数据汇总.md
  - 我的第一个Dockerfile : blog/2019-03-08-我的第一个Dockerfile.md
  - 给你的linux创建一个回收站 : blog/2019-04-27-给你的linux创建一个回收站.md
  - 由reads_count数计算TPM和FPKM: blog/2020-10-28-由reads_count数计算TPM和FPKM.md
  - 获取启动子序列 : blog/2021-08-22-获取启动子序列.md
  - 测试fast_zlib : blog/2024-05-06-测试fast_zlib.md
  - 利用贝叶斯定理判断SNV : blog/2024-05-10-利用贝叶斯定理判断SNV.md
