site_name: biolxy的知识库
site_url: https://biolxy.github.io/
site_author: biolxy
theme:
  name: material #主题</code>
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - offline


# 文档布局
nav:
- Home: index.md
- 博客:
  - Linux安装rar解压软件: blog/2018-12-18-Linux安装rar解压软件.md
  - git开发功能分支标准流程: blog/2018-12-4-git开发功能分支标准流程.md
  - 简单的markdown博客的测试: blog/2018-7-30-简单的markdown博客的测试.md
  - Github个人博客搭建记录: blog/2018-7-31-Github个人博客搭建记录.md
  - 你用的是哪个版本的rename: blog/2018-8-15-你用的是哪个版本的rename.md
  - 生物信息学常用的Linux命令: blog/2018-8-1-生物信息学常用的Linux命令.md
  - 初识GeneSignature : blog/2018-8-3-初识GeneSignature.md
  - 统计学中常用的RR-OR-HR的含义及区别: blog/2018-8-5-统计学中常用的RR-OR-HR的含义及区别.md
  - 将cd和ls两个命令组合起来使用: blog/2018-9-12-将cd和ls两个命令组合起来使用.md
  - 基于已有的image创建dockerimages : blog/2018-9-19-基于已有的image创建dockerimages.md
  - 你是否工作的开心？: blog/2018-9-21-你是否工作的开心？.md
  - 软件著作权申请流程: blog/2018-9-21-软件著作权申请流程.md
  - PyClone的安装报错及解决: blog/2018-9-4-PyClone的安装报错及解决.md
  - R语言使用: blog/2018-9-5-R语言使用.md
  - 开源编程数据汇总: blog/2019-01-17-开源编程数据汇总.md
  - 我的第一个Dockerfile : blog/2019-03-08-我的第一个Dockerfile.md
  - 给你的linux创建一个回收站 : blog/2019-04-27-给你的linux创建一个回收站.md
  - 由reads_count数计算TPM和FPKM: blog/2020-10-28-由reads_count数计算TPM和FPKM.md
  - 获取启动子序列 : blog/2021-08-22-获取启动子序列.md
  - 测试fast_zlib : blog/2024-05-06-测试fast_zlib.md
  - 利用贝叶斯定理判断SNV : blog/2024-05-10-利用贝叶斯定理判断SNV.md