site_name: biolxy的知识库
site_url: https://biolxy.github.io/
site_author: biolxy
copyright: Copyright © 2024 biolxy
repo_name: biolxy
theme:
  name: material # 主题
  # [切换日间模式和夜间模式]
  # ref: https://zhuanlan.zhihu.com/p/685390406  https://eric2003.github.io/Prometheus/home/
  palette:
    # 日间模式
    - scheme: default
      # 主颜色
      primary: indigo
      # 链接等可交互元件的高亮色
      accent: orange
      toggle:
        # 图标
        icon: material/weather-night
        # 鼠标悬浮提示
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    # 使用 Tab 来进行分类
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    - navigation.top
    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    - navigation.indexes
    # 打开 Tab 时左侧目录全部展开
    - navigation.expand
    # 搜索输入一些字母时推荐补全整个单词
    - search.suggest
    # 搜索的关键词文章加入高亮
    - search.highlight
    # 可以通过按钮复制代码
    - content.code.copy
    # [点击按钮跳转至 GitHub 修改 Markdown 源文件]
    - content.action.edit
  language: zh # 一些提示性的文字会变成中文
  icon:
    # [添加 GitHub 仓库]
    repo: https://github.com/biolxy
markdown_extensions:
  # Python Markdown
  - abbr
  - tables
  - attr_list
  - def_list
  # [Markdown footnote 语法支持]
  - footnotes
  # [Markdown 提示]
  - admonition
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
      # Latex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      # 显示行号
      linenums: true
      # 显示编程语言名称
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - search
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: full
      authors_file: .authors.yml
      authors: true
  - offline
  - tags  # 给单篇文章添加标签



extra:
  # [添加社交网络图标和链接]
  # name 会在鼠标悬浮时提示
  social: # icons
    - name: GitHub | biolxy
      icon: fontawesome/brands/github
      link: https://github.com/biolxy

# 文档布局
nav:
  - Home: index.md
  - Blog:
      - blog/index.md
  - 肿瘤基因检测:
      0.背景知识 Background knowledge: NGS/0.Background-knowledge.md
      1.序列比对 reads align: NGS/1.reads-align.md
      2.序列去重 mark/remove dup reads: NGS/2.remove-mark-dup-reads.md
      3.质控 QC: NGS/3.fastp-bam-qc.md
      4.变异检测 somatic mutation calling: NGS/4.somatic-mutation-calling.md
      5.注释 annotate: NGS/5.annotate.md
      6.signature: NGS/6.signature.md
      7.Fusion 基因融合: NGS/7.Fusion.md
      8.MSI 微卫星不稳定: NGS/8.MSI.md
      9.TMB: NGS/9.TMB.md
      10.HLAtype: NGS/10.HLAtype.md
      11.Neoantigen: NGS/11.Neoantigen.md
      12.HLALOH: NGS/12.HLALOH.md
      13.tumor abundance clone: NGS/13.tumor-abundance-clone.md
      14.HRD: NGS/14.HRD.md
      15.ctDNA MRD: NGS/5.MRD.md
      16.RNA: NGS/5.RNA.md
      17.CNV: NGS/17.CNV.md
      18.污染判定: NGS/18.conta.md
      19.医学知识库: NGS/19.Medical-knowledge.md
      20.自动化报告: NGS/20.report.md
      21.workflow: NGS/21.workflow.md
      22.数据传输存储: NGS/22.data.md
      23.性别判定: NGS/23.gender.md
      24.性能验证: NGS/24.pv.md
      25.行业相关: NGS/25.industry.md

